### ISSUE TITLE
possible to estimate fixed effect?

### ISSUE THREAD

**Issue by roninsightrx** [LAPKB/Pmetrics#146]
I was wondering if it is possible to estimate a fixed parameter, e.g. for covariate effects. From the introductory slides and the help I can't figure out how to do that. 

What I mean is e.g. a model where we want to estimate the effect magnitude `TH1` of a covariate:

```
#Pri
Ke, 0, 3
V0, 20, 120
KCP, 0, 5
KPC, 0, 5
TH1, 1.0

#Cov
WEIGHT

#Sec
V=V0*(WEIGHT/70)**TH1
CL=V*Ke
Q=V*KCP
V2=Q/KPC
```

From the documentation, it seems one can only fix TH1 to a known value (as done above), or estimate the non-parametric distribution (by providing min/max values). But how can we estimate a single value for `TH1`?

**Comment by Trepon** [comment]
Your example should work I think. The value is only fixed if it is followed by "!":
`TH1, 1.0!`
In your case, TH1 will be estimated to a single (random) value.

**Comment by mnneely** [comment]
That’s correct. If you supply only a single number for a parameter in the #PRI block, Pmetrics will consider it as a random variable with zero variance, i.e. unknown but the same for every subject. The value you use will be the starting value in cycle 1 of the estimation. If you add an “!” to the declaration, as Trepon said, then Pmetrics treats the parameter as a constant, i.e. it fixes the value for every subject in the population to whatever you put in the declaration.

As another point, looking at your example model code, please be aware that secondary values (e.g. CL = V*Ke in your code) do not have distributions estimated for them in the output. They are only convenience parameters to make model files more readable. So in your case, you won’t get an estimate for CL. If you want to parameterize your algebraic model (no differential equations) in terms of CL, then put CL in the #PRI block and put Ke = CL/V in the #SEC block. Same for Q and V2. That will trigger the right algebraic model because Pmetrics looks first for Ke and V in #PRI or #SEC, and then KCP, KPC, and Ka in either block. Depending on which it finds, it writes the correct algebraic solutions. In your case it finds the variables all in #PRI, so it doesn’t need CL, Q or V2, unless you are using them elsewhere in your model file.

**Comment by roninsightrx** [comment]
Hi both, thanks for clear explanations! I probably thought it was held constant because I couldn't find the value of that estimated parameter in the output object (e.g. `run3 <- PM_load("run3/1")`). Can you point me to where in the output object I can find the value of that estimated parameter?

Update: I ultimately found the value for the TH1 parameter in file OUTT0001. Is it somewhere in the output object as well?

**Comment by mnneely** [comment]
https://lapkb.github.io/Pmetrics/reference/PM_final.html

`res1 <- PM_load(1)`
`res1$final$$popRanFix`
