### ISSUE TITLE
PMfit$run error

### ISSUE THREAD

**Issue by BoburaII** [LAPKB/Pmetrics#178]
Hello, 
Executing PMfit$run returns the error below:

> ffit$run(cycles = 500)
Error in block[[i]]$constant : $ operator is invalid for atomic vectors

Running on Pmetrics 2.1, R 4.3.1, M1 macOS

**Comment by mnneely** [comment]
Hi, you'll need to provide more context for us to help. What does your model object look like? Thanks.

**Comment by BoburaII** [comment]
Hi, the model object as part of a workflow is below:

#dir
setwd("~/Pmetrics/FluE/src")

#data file
fdata <- PM_data$new("flu_data.csv")

#model
fmod <- PM_model$new(list(
  pri = list(
    Ka = ab(0.1, 0.9),
    Ke = ab(0.001, 0.1),
    V = ab(30, 120),
    Tlag1 = ab(0, 4)
  ),
  cov = list("WT", "AFRICA", "AGE", "GENDER", "HEIGHT"),
  lag = list("Tlag(1) = Tlag1"),
  out = list(
    Y1 = list(
      value = "X(2)/V",
      err = list(
        model = proportional(5),
        assay = c(0.02, 0.05, -0.0002, 0)
      )
    )
  )
))

#fit model
ffit <- PM_fit$new(fdata, fmod)

setwd("../Runs")

ffit$run(cycles = 500)

Used to run fine; then, recently updated R (version 4.3.1) and Pmetrics (version 2.1). PM_fit$run now returns the error:

Error in block[[i]]$constant : $ operator is invalid for atomic vectors

I appreciate your help with this. 
Thanks

**Comment by mnneely** [comment]
I'm impressed that you are writing the model in the list form! :) Sorry that the error message wasn't helpful. I think the problem is in two places:

1. To have the ability to specify covariates as interpolated (default) or piece-wise constant, we changed the structure of that block a bit. It should be:
```
cov = list(
      covariate("WT"),
      covariate("AFRICA"),
      covariate("AGE"),
      covariate("GENDER"),
      covariate("HEIGHT")
    )
```
2.  Likewise, in the assay error declaration, to implement the ability to have the model assay polynomial override values in the data, we had to change the structure of that as well. It should now be:

```
Y1 = list(
  value = "X(2)/V",
  err = list(
    model = proportional(5),
    assay = errorPoly(c(0.02, 0.05, -0.0002, 0))
   )
)
```
We've also implemented a new Shiny model builder app which can help.  It is launched with `build_model()`. All of this is [documented](https://lapkb.github.io/Pmetrics/articles/models.html) for instruction and reference. If you use the model builder, it will insert a "token" in the equations, which allows you to use algebraic equations, but still has the differential equations to allow plotting of the model structure and be more transparent about how drug is moving. In the older Pmetrics, with algebraic models, the equations were buried and it wasn't very clear what they were.

All together, you can try it out with this:

`build_model(NPex$model)`

Once the app launches, if you visit each sidebar element, you'll see the defaults. You'll also see the model diagram. Lastly, if you click the Model List tab after visiting all the sidebar elements, you'll see the entire list code which you can copy or save to the familiar .txt file version.

```
PM_model$new(
  list(
    pri = list(
      Ka = ab(0.1, 0.9),
      Ke = ab(0.001, 0.1),
      V = ab(30, 120),
      Tlag1 = ab(0, 4)
    ),
    cov = list(
      covariate("WT"),
      covariate("AFRICA"),
      covariate("AGE"),
      covariate("GENDER"),
      covariate("HEIGHT")
    ),
    lag = list(
      "TLAG(1) = Tlag1"
    ),
    eqn = list(
      "{algebraic: Ka,Ke,V,2}",
      "dX[1] = BOLUS[1] - Ka*X[1]",
      "dX[2] = RATEIV[1] + Ka*X[1] - Ke*X[2]"
    ),
    out = list(
      Y1 = list(
        val = "X[2]/V",
        err = list(
          model = proportional(5),
          assay = errorPoly(c(0.02, 0.05, -2e-04, 0))
        )
      )
    )
  )
)
```

**Comment by BoburaII** [comment]
Thank you, Prof. Neely for the detailed response and instruction on the Shiny app.
Incorporating these changes solves the problem. A very nice elaborate report is generated upon completion of the run :)

Again, thank you.

**Comment by mnneely** [comment]
Thanks for the kind words and for letting me know it worked! I'll marked this as closed.
