### ISSUE TITLE
Issue in Installation of Pmetrics from GITHUB

### ISSUE THREAD

**Issue by harishkaushikbugworks** [LAPKB/Pmetrics#45]
I have followed the instruction provided in http://www.lapk.org/Pmetrics_install.php
however, i face the following issue as shown in the screen shot, unable to proceed further from last 10 times, i treid some thing nothing worked

can any one help
![isse while installation](https://user-images.githubusercontent.com/49284633/108948967-83470980-7689-11eb-8d15-db02beaf8858.jpg)

**Comment by Siel** [comment]
Please try again selecting the option 3 (None) when the installations asks you which packages do you want to update.

**Comment by CRquantum** [comment]
There might be several options.
1. Uninstall that package (perhaps no need to uninstall it), then anyway install it using "dependences = TRUE". Eg, install.packages("package name", dependencies = TRUE)
2. You might also try option 2, CRAN package only. Then, in the pop up windows, if it asks things like  it requires compile on the local machine yes or no? Choose Yes. In the following pop up windows, choose Yes again. Anyway, choose Yes.  It does take a while for the packages to be installed or updated since they needs to be compiled on your machine, but once it finished it usually solves the problem. 

In addition, if you have R version 4.x.x, please install Rtools 4.0. 
If you have R version 3.6.3, please install Rtools35, https://cran.r-project.org/bin/windows/Rtools/history.html

For gfortran, I suggest that you may want to install stawberry perl, https://strawberryperl.com/   and please also note that you find stawbeery dir and need to put things like  C:\Strawberry\c\bin\   in you system's environment path, on top of other items which may also contain gfortran.exe. Point is to let Pmetric find the gfortran.exe in stawberry dir first so that it can use it. 
![Screenshot 2021-03-11 225051](https://user-images.githubusercontent.com/52009942/110903716-b8c03980-82bc-11eb-9c89-ed9eb82975fa.png)

**Comment by Siel** [comment]
@harishkaushikbugworks is this issue solved?

**Comment by Siel** [comment]
For the time being, I'm going to close the issue, please feel free to re-open if necessary
