### ISSUE TITLE
Prior is not respected when argument is a string

### ISSUE THREAD

**Issue by mhovd** [LAPKB/Pmetrics#84]
As the title indicates, Pmetrics will not use a prior for a run when supplying `prior = "DEN0001"` as input.
Tested on R `4.1.3` and Pmetrics version 2.

Here is a minimal, working example
```r
library(Pmetrics)

# Run using the built-in example data
writeLines(model, "model.txt")
mod = PM_model$new("model.txt")
dat = PM_data$new(mdata.1)
fit = PM_fit$new(data = dat, model = mod)
fit$run()

# Copy DEN0001 to current directory, and attempt to use as prior
file.copy(from = "1/outputs/DEN0001", to = getwd())
list.files()
[1] "1"         "DEN0001"   "model.txt"

fit$run(prior = "DEN0001")
```
The HTML report will then indicate that a uniform distribution was used.
Using `fit$run(prior = 1)`, where 1 is the run number in the current directory, will correctly provide a prior distribution.

The following should be evaluated:
- Pmetrics should be able to take `prior = "DEN0001`
- When supplying a filename as argument to `prior`, if the file is not found, the run should not execute, but stop with a warning, just like if a model- or datafile is not found.

**Comment by Siel** [comment]
Thank you @mhovd!

@mnneely should I implement it this way?

**Comment by mnneely** [comment]
It was implemented that way as an alternative to supplying the run number. Yes, if we can fix it so that it works that way again, that would be good. Most will not use it, but good to have the flexibility.


On Aug 3, 2022, at 6:26 AM, Julian Otalvaro ***@***.******@***.***>> wrote:



Thank you @mhovd<https://urldefense.com/v3/__https://github.com/mhovd__;!!LIr3w8kk_Xxm!vcGVhazVIU4Qkdu8d78AXqvI29axM00fpM_AmtgzN2YZLpVIwMlpPt_Tn02ri2jionYkvggeJXzKsI33ZPg2tqc$>!

@mnneely<https://urldefense.com/v3/__https://github.com/mnneely__;!!LIr3w8kk_Xxm!vcGVhazVIU4Qkdu8d78AXqvI29axM00fpM_AmtgzN2YZLpVIwMlpPt_Tn02ri2jionYkvggeJXzKsI33C7Xxa6A$> should I implement it this way?

**Comment by mhovd** [comment]
An additional advantage of allowing filename as an input would be the ability to define custom prior distributions for runs.
It would require some very finicky editing of the `DEN0001` file, but I'm happy to help write a wrapper for it.

**Comment by Siel** [comment]
I just implemented this functionality here: https://github.com/LAPKB/Pmetrics/blob/96e786d770a0f305f2068b5b0693dc1280e48056/R/PMrun.R#L184

Please let me know if it works as you intended.

Thanks!

p.s: I'll close the issue, please feel fre to re-open if that is the case.
